apiVersion: v1
kind: Template
labels:
  template: jenkins-master-s2i
metadata:
  annotations:
    description: Creates a Jenkins master using S2I for installing plugins and configuring Jenkins
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-master-s2i
parameters:
- description: Git source URI for Jenkins S2I
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/giuseppetanzi/jenkins-swarm.git
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
  value: master
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 512Mi
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: Label for slave pods which are used by Jenkins to discover slave pods and assign jobs to them
  displayName: Jenkins Slave Label
  name: SLAVE_LABEL
  required: true
  value: jdk8
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: SLAVE_REPO_URL
  value: https://github.com/giuseppetanzi/jenkins-swarm.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: SLAVE_REPO_CONTEXTDIR
  value: slave
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: SLAVE_REPO_REF
  value: master
- description: Jenkins master username.
  displayName: Jenkins username
  name: JENKINS_USERNAME
  value: admin
- description: Jenkins master password
  displayName: Jenkins password
  name: JENKINS_PASSWORD
  value: password
- description: Number of executors per slave
  displayName: Jenkins slave executors
  name: EXECUTORS
  value: '3'
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: jenkins
    name: jenkins
- apiVersion: v1
  kind: Service
  metadata:
    name: jenkins
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jnlp
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      application: jenkins-master
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: jenkins
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: jenkins
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins:latest
    resources:
      limits:
        memory: ${MEMORY_LIMIT}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      secrets: []
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jenkins:1
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: jenkins
  spec:
    replicas: 1
    selector:
      application: jenkins-master
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: jenkins-master
      spec:
        containers:
        - env:
          - name: JENKINS_PASSWORD
            value: ${JENKINS_PASSWORD}
          image: jenkins
          imagePullPolicy: Always
          name: jenkins
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          emptyDir:
            medium: ""
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: jenkins:latest
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      slave-directory: /var/lib/jenkins
    labels:
      role: jenkins-slave
    name: jenkins-swarm-slave
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-swarm-slave
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-swarm-slave:latest
    resources: {}
    source:
      contextDir: ${SLAVE_REPO_CONTEXTDIR}
      git:
        ref: ${SLAVE_REPO_REF}
        uri: ${SLAVE_REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: jenkins-slave
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources:
    triggers:
      -
        type: ConfigChange
      -
        type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - jenkins-slave
          from:
            kind: ImageStreamTag
            name: 'jenkins-swarm-slave:latest'
    replicas: 1
    selector:
      application: jenkins-swarm-slave
      deploymentconfig: jenkins-swarm-slave
    template:
      metadata:
        labels:
          application: jenkins-swarm-slave
          deploymentconfig: jenkins-swarm-slave
      spec:
        volumes:
          -
            name: jenkins-slave-data
            emptyDir:
        containers:
          -            
            ports:
            - containerPort: 5555
              protocol: TCP
            name: jenkins-slave
            env:
              -
                name: JENKINS_USERNAME
                value: ${JENKINS_USERNAME}
              -
                name: JENKINS_PASSWORD
                value: ${JENKINS_PASSWORD}
              -
                name: JENKINS_SERVICE_HOST
                value: jenkins
              -
                name: JENKINS_SERVICE_PORT
                value: '8080'
              -
                name: SLAVE_LABEL
                value: ${SLAVE_LABEL}
              -
                name: EXECUTORS
                value: ${EXECUTORS}
              -
                name: JENKINS_CONTEXT_PATH
            resources:
            volumeMounts:
              -
                name: jenkins-slave-data
                mountPath: /var/lib/jenkins
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext:
